import re
import numpy as np
from typing import List, Dict, Any, Tuple
from loguru import logger
from src.hybrid_retriever import Citation

class CitationValidator:
    """
    Parses, validates, and cleans inline citations generated by the LLM.
    Enforces that the model only references retrieved source passages with semantic alignment.
    """
    def __init__(self, retriever: Any = None, warning_threshold: float = 0.65, reject_threshold: float = 0.50, replace_invalid: bool = True) -> None:
        self.retriever = retriever
        self.warning_threshold = warning_threshold
        self.reject_threshold = reject_threshold
        self.replace_invalid = replace_invalid
        self.citation_pattern = re.compile(r"\[Citation\s+(\d+)\]")
        self.model = None
        self.warnings = []
        self.citation_precision = 1.0
        self.generated_count = 0
        self.semantic_alignment_scores = []
        
        if retriever is not None:
            is_hybrid_retriever = False
            if hasattr(retriever, "_spec_class") and getattr(retriever._spec_class, "__name__", "") == "HybridRetriever":
                is_hybrid_retriever = True
            elif retriever.__class__.__name__ == "HybridRetriever":
                is_hybrid_retriever = True
                
            if is_hybrid_retriever:
                self.model = retriever.vector_retriever.model
            elif hasattr(retriever, "vector_retriever") and not hasattr(retriever, "encode"):
                self.model = retriever.vector_retriever.model
            elif hasattr(retriever, "model") and not hasattr(retriever, "encode"):
                self.model = retriever.model
            else:
                self.model = retriever

    def validate(self, answer_text: str, available_citations: List[Citation], vector_context: List[Dict[str, Any]] = None) -> Tuple[str, List[Citation], List[str]]:
        """
        Extracts citations from the answer text, validates them, and removes/replaces hallucinated ones.
        Returns:
            - validated_answer: cleaned/replaced answer string
            - used_citations: list of Citation objects that were actually validated and used
            - invalid_citations: list of raw citation strings that were invalid (hallucinated or mismatched)
        """
        self.warnings = []
        self.citation_precision = 1.0
        self.semantic_alignment_scores = []
        
        # Clean up any bibliography/metadata details trailing the citation tag (e.g. [Citation 1]: Title...)
        answer_text = re.sub(r"\[Citation\s+(\d+)\]\s*:\s*[^\[\n]*(?:arXiv|Section|Pages|et al\.)[^\[\n]*", r"[Citation \1]", answer_text)
        
        # Count total generated citation tags
        generated_count = len(self.citation_pattern.findall(answer_text))
        self.generated_count = generated_count
        
        # Split answer into sentences
        # Splitting on punctuation followed by whitespace, keeping separators using capturing parenthesis
        parts = re.split(r'((?<=[.!?])\s+)', answer_text)
        sentences = parts[::2]
        separators = parts[1::2]
        
        used_indices = set()
        invalid_citations = []
        
        # Build map of chunk_id -> chunk paragraphs
        chunk_paragraphs = {}
        if vector_context:
            for chunk in vector_context:
                c_id = chunk.chunk_id if hasattr(chunk, "chunk_id") else chunk.get("chunk_id")
                c_text = chunk.text if hasattr(chunk, "text") else chunk.get("text", "")
                if c_id:
                    # Split into paragraphs
                    paragraphs = [p.strip() for p in c_text.split("\n\n") if p.strip()]
                    if not paragraphs:
                        paragraphs = [c_text]
                    chunk_paragraphs[c_id] = paragraphs

        # Lazy load BGE model if vector_context is provided and not loaded yet
        if vector_context and self.model is None:
            try:
                from src.llm import get_embedding_model
                model_name = "BAAI/bge-small-en-v1.5"
                if self.retriever and hasattr(self.retriever, "vector_retriever"):
                    model_name = self.retriever.vector_retriever.model_name
                self.model = get_embedding_model(model_name)
            except Exception as e:
                logger.error(f"Failed to load sentence transformer in citation validator: {e}")

        # Embedding cache
        sentence_embs = {}
        para_embs = {}
        
        # Batch precompute embeddings for all clean sentences and cited paragraphs to speed up validation
        if vector_context and self.model is not None:
            all_clean_sentences = []
            cited_chunk_ids = set()
            
            for sentence in sentences:
                sentence_matches = self.citation_pattern.findall(sentence)
                if sentence_matches:
                    clean_sentence = re.sub(r"\[Citation\s+\d+\]", "", sentence).strip()
                    clean_sentence = re.sub(r"\s+", " ", clean_sentence)
                    if clean_sentence:
                        all_clean_sentences.append(clean_sentence)
                    for num_str in sentence_matches:
                        idx = int(num_str) - 1
                        if 0 <= idx < len(available_citations):
                            citation = available_citations[idx]
                            cited_chunk_ids.add(citation.chunk_id)
            
            # Map paragraphs to embed
            unique_paras = []
            para_keys_map = []
            for chunk_id in cited_chunk_ids:
                if chunk_id in chunk_paragraphs:
                    for p_idx, para in enumerate(chunk_paragraphs[chunk_id]):
                        para_key = f"{chunk_id}_{p_idx}"
                        unique_paras.append(para)
                        para_keys_map.append((para_key, para))
            
            # Batch encode sentences
            if all_clean_sentences:
                try:
                    unique_sentences = list(set(all_clean_sentences))
                    sent_vectors = self.model.encode(unique_sentences, normalize_embeddings=True)
                    for s_text, s_vec in zip(unique_sentences, sent_vectors):
                        sentence_embs[s_text] = s_vec
                except Exception as e:
                    logger.error(f"Error batch encoding sentences: {e}")
                    
            # Batch encode paragraphs
            if unique_paras:
                try:
                    unique_para_texts = list(set(unique_paras))
                    para_vectors = self.model.encode(unique_para_texts, normalize_embeddings=True)
                    text_to_vector = dict(zip(unique_para_texts, para_vectors))
                    for para_key, para_text in para_keys_map:
                        para_embs[para_key] = text_to_vector[para_text]
                except Exception as e:
                    logger.error(f"Error batch encoding paragraphs: {e}")
        
        processed_sentences = []
        
        for sentence in sentences:
            sentence_matches = self.citation_pattern.findall(sentence)
            processed_sentence = sentence
            
            if sentence_matches:
                # Clean sentence text (exclude citation tags for embedding)
                clean_sentence = re.sub(r"\[Citation\s+\d+\]", "", sentence).strip()
                clean_sentence = re.sub(r"\s+", " ", clean_sentence)
                
                for num_str in sentence_matches:
                    idx = int(num_str) - 1
                    tag = f"[Citation {num_str}]"
                    
                    if 0 <= idx < len(available_citations):
                        citation = available_citations[idx]
                        chunk_id = citation.chunk_id
                        
                        is_aligned = True
                        similarity_score = 1.0 # Default if no model or text
                        
                        if self.model is not None and chunk_id in chunk_paragraphs and clean_sentence:
                            try:
                                # Embed sentence
                                if clean_sentence not in sentence_embs:
                                    sentence_embs[clean_sentence] = self.model.encode(
                                        [clean_sentence], normalize_embeddings=True
                                    )[0]
                                sent_vector = sentence_embs[clean_sentence]
                                
                                # Embed paragraphs and find max similarity
                                paragraphs = chunk_paragraphs[chunk_id]
                                similarities = []
                                for p_idx, para in enumerate(paragraphs):
                                    para_key = f"{chunk_id}_{p_idx}"
                                    if para_key not in para_embs:
                                        para_embs[para_key] = self.model.encode(
                                            [para], normalize_embeddings=True
                                        )[0]
                                    para_vector = para_embs[para_key]
                                    sim = float(np.dot(sent_vector, para_vector))
                                    similarities.append(sim)
                                
                                similarity_score = max(similarities) if similarities else 0.0
                                self.semantic_alignment_scores.append(similarity_score)
                                
                                # Threshold check
                                if similarity_score < self.reject_threshold:
                                    is_aligned = False
                                    invalid_citations.append(f"{tag} (Semantic mismatch: score {similarity_score:.2f})")
                                    # Replace or strip tag
                                    replacement = "[Invalid Citation Removed]" if self.replace_invalid else ""
                                    processed_sentence = processed_sentence.replace(tag, replacement)
                                    logger.info(f"Rejected citation {tag} (similarity {similarity_score:.2f} < {self.reject_threshold}) in sentence: '{clean_sentence}'")
                                elif similarity_score < self.warning_threshold:
                                    # Warn but accept
                                    self.warnings.append(f"{tag} (Semantic warning: score {similarity_score:.2f})")
                                    logger.warning(f"Citation warning {tag} (similarity {similarity_score:.2f} < {self.warning_threshold}) in sentence: '{clean_sentence}'")
                            except Exception as e:
                                logger.error(f"Error during semantic alignment check: {e}")
                        
                        if is_aligned:
                            used_indices.add(idx)
                    else:
                        # Out of bounds index
                        invalid_citations.append(tag)
                        replacement = "[Invalid Citation Removed]" if self.replace_invalid else ""
                        processed_sentence = processed_sentence.replace(tag, replacement)
            
            processed_sentences.append(processed_sentence)
            
        # Reconstruct the answer by alternate zipping to preserve the exact whitespace separators
        reconstructed = []
        for i in range(len(processed_sentences)):
            reconstructed.append(processed_sentences[i])
            if i < len(separators):
                reconstructed.append(separators[i])
        validated_answer = "".join(reconstructed)
        
        # Build used citations list sorted by index
        used_citations = [available_citations[idx] for idx in sorted(list(used_indices))]
        
        # Clean spacing issues, empty brackets, etc.
        validated_answer = re.sub(r"\[\s*\]", "", validated_answer)
        # Clean double spaces
        validated_answer = re.sub(r"[ \t]+", " ", validated_answer)
        # Clean multiple vertical newlines (reduce 3+ newlines to 2)
        validated_answer = re.sub(r"\n{3,}", "\n\n", validated_answer)
        validated_answer = validated_answer.replace(" ,", ",").replace(" .", ".")
        validated_answer = validated_answer.strip()
        
        # Calculate citation precision based on pattern count in final text
        final_tags_count = len(self.citation_pattern.findall(validated_answer))
        self.citation_precision = final_tags_count / generated_count if generated_count > 0 else 1.0
        
        return validated_answer, used_citations, invalid_citations
